site_name: My Books
nav:
  - 목록 : index.md
  - 그레이트 마이드셋 : great_mindset.md
  - 소프트웨어 아키텍처 문서화 : software_architecture_documentation.md

theme: material
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc : 
      permalink :  true